pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                sh './deployment/scripts/build.sh'
            }
        }

        stage('Push') {
            steps {
                sh './deployment/scripts/push.sh'
            }
        }

        stage("Deploy") {
            steps {
                ansiblePlaybook credentialsId: 'ansible-ssh-web', disableHostKeyChecking: true, installation: 'Ansible',
                 inventory: 'deployment/ansible/hosts.inv', playbook: 'deployment/ansible/deploy.yaml',
                 extras: "-e aws_ecr_login_repository=${REPOSITORY}"
            }
        }
    }
}

