---
- name: Deploying
  hosts: staging
  become: yes
  gather_facts: False

  tasks:
    - name: login
      ansible.builtin.shell: "aws ecr get-login-password | docker login --username AWS --password-stdin {{ aws_ecr_login_repository }}"
      when: aws_ecr_login_repository is not none and aws_ecr_login_repository != ''

    - name: copy docker-compose.yaml
      copy:
        src: ../docker-compose.yaml
        dest: ./docker-compose.yaml
        owner: ubuntu
        group: ubuntu
        mode: 0775

    - name: copy .env file
      copy:
        src: ../../.env
        dest: ./.env
        mode: 0644

#    - name: docker compose down
#      docker_compose:
#        project_src: ./
#        state: absent

    - name: deleting docker objects 1
      docker_host_info:
        images: yes
        containers: yes
      register: docker_objects

    - name: deleting docker objects 2
      docker_container:
        name: "{{ item.Id }}"
        state: absent
      loop: "{{ docker_objects.containers }}"
      loop_control:
        label: "{{ item.Id }}"

    - name: deleting docker objects 3
      docker_image:
        name: item.RepoTags | first
        state: absent
        force_absent: yes
      loop: "{{ docker_objects.images }}"
      loop_control:
        label: "{{ item.RepoTags | first }}"

    - name: docker compose up
      docker_compose:
        project_src: ./
      environment:
        IMAGE: "{{image}}"
