---
- name: Deploying
  hosts: staging
  become: yes
  gather_facts: False

  vars:
    aws_ecr_login_repository: "{{aws_ecr_login_repository}}"

  tasks:
    - name: login
      ansible.builtin.shell: "aws ecr get-login-password | docker login --username AWS --password-stdin {{ aws_ecr_login_repository }}"
      when: aws_ecr_login_repository is not none and aws_ecr_login_repository != ''

    - name: export repository variable
        shell: "export REPOSITORY={{aws_ecr_login_repository}}"

    - name: copy docker-compose.yaml
      copy:
        src: ../docker-compose.yaml
        dest: ./docker-compose.yaml
        owner: ubuntu
        group: ubuntu
        mode: 0775

    - name: docker compose down
      docker_compose:
        project_src: ./
        state: absent

    - name: docker compose up
      docker_compose:
        project_src: ./
