---
- name: Deploying
  hosts: staging
  become: yes

    - name: push docker-compose.yaml
      copy:
        src: ../docker-compose.yaml
        dest: ./docker-compose.yaml
        owner: ubuntu
        group: ubuntu
        mode: 0775

    - name: docker compose down
      docker_compose:
        project_src: ./
        state: absent

    - name: docker compose up
      docker_compose:
        project_src: ./
